const BORDERS = {
  RADIUS: 16,
  THICKNESS: 8,
  PADDING_X: 16,
  PADDING_Y: 16,
  ANIMATION_DURATION: 0.7,
  BORDER_WIDTH_MULTIPLIER: 1.5,
  RESIZE_DEBOUNCE_DELAY: 100,
  RESIZE_OBSERVER_DEBOUNCE_DELAY: 150,
  STROKE_DASHARRAY_LARGE_VALUE: 10000,
}

export { BORDERS }
